### PR TITLE
➕ add storybook

### PR DESCRIPTION
**Pull request by RonjaMeinecke**
• install storybook `npx sb init`
https://storybook.js.org/docs/react/get-started/install
• remove example stories folder and add `components` folder instead
• add example Button component
• set stories folder in `.storybook/main.js`
• load example component in `pages/index.tsx`
• ignore /storybook-static
• add `.eslintignore` and ignore storybook-static
• ignore eslintcache & storybook-static in `.gitignore`
• ignore storybook-static in `.prettierignore`
• clean up Home.module.css
• clean up index.tsx and import Button component

### CODE REVIEW

**Review by saschahaselhuhn — APPROVED** [review]
gj

**Review by christophvogel — APPROVED** [review]
GJ 👍

**Review by fre-ben — APPROVED** [review]
LGTM 💯

**Review by JuKahl — APPROVED** [review]
GJ 🚀

**Review by cboenke — APPROVED** [review]
LGTM 🚀

**Comment by SilviaBarcellini** [comment]
Good job! 👍

**Review by DNaunin — APPROVED** [review]
Good Job! 🚀

**Review by m-wiemers — APPROVED** [review]
It smells like Australia 🦘

**Review by sweisz — APPROVED** [review]
LGTM 👍

**Pull request merged**
